### ISSUE TITLE
拍卖会等待时长呈负数无限增长

### ISSUE THREAD

**Issue by youlanan** [MyXiaoNan/nonebot_plugin_xiuxian_2_pmv#73]
错误如下，最终重启并向计算式加入abs()，但尚不清楚问题原因，以及是否还会复现

![01](https://github.com/user-attachments/assets/f35bad39-0848-439a-ac15-849b91b89ce7)
![02](https://github.com/user-attachments/assets/178e426f-8de7-4bc2-b3c9-5c1fe9475682)

![...](https://n.sinaimg.cn/sinakd20109/763/w1000h563/20210514/735d-kpzzqna0496233.jpg)

![歪比巴卜](https://github.com/user-attachments/assets/5785b337-f4c1-423c-bce4-997c62a697f3)

![阿巴](https://github.com/user-attachments/assets/e64b902e-46bb-46b0-8606-64256cc25c9c)

**Comment by PackageInstaller** [comment]
你这是跑的是最新的commit吗

**Comment by PackageInstaller** [comment]
暂时没人回报这个问题了，先close,如果有了再开
